feat:修复启用ipv6时报错，增加更新chnroute的脚本

diff --git a/tproxy b/tproxy
--- a/tproxy
+++ b/tproxy
@@ -190,7 +190,7 @@ start_iptables_post_rules(){
 
 start_iptables_tproxy_mode(){
 	local loopback_addr
-	is_ipv4_ipts $1 && loopback_addr="127.0.0.1" || loopback_addr="::1:"
+	is_ipv4_ipts $1 && loopback_addr="127.0.0.1" || loopback_addr="::1"
 	
 	local netfamily
 	is_ipv4_ipts $1 && netfamily="inet" || netfamily="inet6"
@@ -332,6 +332,20 @@ status(){
 	tcp_port_is_exists $proxy_tcpport && echo "ipt2socks/tcp: $(color_green '[running]')" ||echo "ipt2socks/tcp: $(color_red '[stopped]')"
 	udp_port_is_exists $proxy_udpport && echo "ipt2socks/udp: $(color_green '[running]')" ||echo "ipt2socks/udp: $(color_red '[stopped]')"
 }	
+
+update_chnroute() {
+    command_is_exists 'curl' || log_error "command not found: curl"
+    local url='http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest'
+    local data; data=$(curl -4sSkL "$url") || log_error "download failed, exit-code: $?"
+    {
+        echo "create chnroute hash:net family inet"
+        echo "$data" | grep CN | grep ipv4 | awk -F'|' '{printf("add chnroute %s/%d\n", $4, 32-log($5)/log(2))}'
+    } >$file_chnroute_set
+    {
+        echo "create chnroute6 hash:net family inet6"
+        echo "$data" | grep CN | grep ipv6 | awk -F'|' '{printf("add chnroute6 %s/%d\n", $4, $5)}'
+    } >$file_chnroute6_set
+}
 	
 		
 main(){
@@ -342,7 +356,8 @@ main(){
 		start)      start ;;
 		stop)       stop ;;
 		status)     status ;;
-		*)          echo "Usage: $0 {start|stop|status}" ;;
+		update-chnroute) update_chnroute;;
+		*)          echo "Usage: $0 {start|stop|status|update-chnroute}" ;;
 	esac
 	return 0
 }
